### ISSUE TITLE
Platba nenalezena po redirectu

### ISSUE THREAD

**Issue by l1zard** [Kdyby/CsobPaymentGateway#15]
Zdravím, všechno mi normálně funguje, ale když má přijít redirect zpátky ke mě, tak mi brána vyhodí tuhle hlášku 

> Platba nenalezena
> Požadovaná platba bohužel neexistuje, nebo vypršela platnost požadavku. Pokoušíte-li se zaplatit objednávku, vraťte se prosím na stránky obchodníka a zaplaťte prosím znovu.

přitom platba normálně projde. Jedu na testovacím prostředí. Děkuji za reakci

**Comment by fprochazka** [comment]
@l1zard Ahoj, můžeš to prosím zkusit nasimulovat pomocí [examples](https://github.com/Kdyby/CsobPaymentGateway/tree/master/examples) ? Používáš [Kdyby/CsobPaygateNette](https://github.com/Kdyby/CsobPaygateNette) nebo máš nějakou vlastní integraci?

**Comment by l1zard** [comment]
@fprochazka Teď něják nechápu co myslíš, nainstaloval jsem si přez composer
"kdyby/csob-payment-gateway" a "guzzlehttp/guzzle" a snažím se to testnout podle dokumentace. + podle paymentStatusu platba byla provedena v pořádku.

**Comment by fprochazka** [comment]
@l1zard no, napsal jsi mi obecný problém, jenže knihovna je nasazena na několika nemalých projektech a nikdo nic takového nehlásí - potřeboval bych tedy, aby ses pokusil se svými klíči si rozběhat examples (jak jsem psal) a na nich problém nasimuloval. Případně alespoň, zkus ukázat kód jak to používáš a cos oproti examples/dokumentaci změnil.

Případně jestli @jiripudil netuší...

**Comment by l1zard** [comment]
@fprochazka Problém solved, moje chyba neměl jsem v návratové url http. Sorry za komplikace můžes to klidně smazat, ale díky za reakce.

**Comment by fprochazka** [comment]
@l1zard mazat to určitě nechci, třeba to někomu pomůže. Jsem rád, že jsi to vyřešil :+1:
