### ISSUE TITLE
Payment phpDoc

### ISSUE THREAD

**Issue by honzalilak** [Kdyby/CsobPaymentGateway#18]
Hi,

method `Payment::getOriginalPayId()` will return `NULL` in some cases, however the phpDoc annotation says it returns string only. This may happen because setting the property `origPayId` is not required. Shouldnt the annotation be `|NULL` for properties that are not required to be set as well as for their getters?

I can make PR but I would like to confirm that you are open to that.

**Comment by fprochazka** [comment]
If there is a state, where the object allows the value to be `NULL` (and it's not a bug), then surely it should be in the phpdoc.
