### ISSUE TITLE
Check merchantData length in encoded state

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/CsobPaymentGateway#21]
Relevant:
- https://github.com/slevomat/csob-gateway/pull/14
- https://github.com/csob/paymentgateway/wiki/eAPI-1.6#-post-httpsapiplatebnibranacsobczapiv16paymentinit-

**Comment by jiripudil** [comment]
@fprochazka This does not suffice? https://github.com/Kdyby/CsobPaymentGateway/blob/cf036b8/src/Payment.php#L612

**Comment by fprochazka** [comment]
I see now, that should be fine then :)
