### ISSUE TITLE
CartItem price

### ISSUE THREAD

**Issue by soukicz** [Kdyby/CsobPaymentGateway#5]
U metody addCartItem je atribut $price a popis "In hundredth of currency units". Z toho bych chápal, že je to cena za kus. V dokumentaci ČSOB je ale uvedeno, že je to celková cena. Nenašel jsem, že by se to někde násobilo kusy (a asi ani nenásobí, protože pak by se muselo řešit zaokrouhlení).

**Comment by jiripudil** [comment]
Je to celková cena. Currency unit (měnová jednotka) je terminus technicus, vůbec to nesouvisí s počtem kusů zboží :)

**Comment by soukicz** [comment]
Třetí argument addCartItem je $quantity

**Comment by jiripudil** [comment]
To se ale imo předává jen kvůli přehledu, který je pak vidět přímo na bráně při platbě. Ta cena je každopádně celková. Jestli ti někde nějaká formulace připadá nejasná, pošli PR :)

**Comment by soukicz** [comment]
Šlo mi jen o to, že posílám cenu a množství - očekával bych tedy, že to je cena za kus.

**Comment by fprochazka** [comment]
@soukiii máš pravdu, to api té třídy je nelogické. Dal bych tam asi raději to násobení, co myslíš?

**Comment by soukicz** [comment]
U násobení ale zase narazíš na zaokrouhlování. Bez násobení dostaneš celkovou částku po zaokrouhlení, což není to samé jako zaokrouhlené částky vynásobené.

**Comment by fprochazka** [comment]
Násobení celých čísel je celkem safe, ne?

**Comment by soukicz** [comment]
To jo. Ale já to musím zaokrouhlit, abych ti to celé číslo mohl dát.

**Comment by fprochazka** [comment]
Hmm.. takže lepší asi bude zůstat u debilního api, ale přidat k tomu nějakou dokumentaci.

**Comment by soukicz** [comment]
Ono nejspíš bude stačit jen přejmenovat ten atribut. Když to bude $totalPriceInCents, tak už to při psaní v IDE bude rovnou vidět

**Comment by fprochazka** [comment]
@soukiii `$priceInCents` už jsem tam jednou málem dal, ale pak jsem se zasekl na tom, jestli se cents dá použít jako univerzální slovo i pro koruny a eura :)

**Comment by soukicz** [comment]
Ono je to víceméně univerzální - https://en.wikipedia.org/wiki/Centi-

**Comment by jiripudil** [comment]
Univerzální pojmenování je "fractional unit", ale to už je zase takové docela neohrabané

**Comment by soukicz** [comment]
Každopádně ale v dokumentaci (i u Spořky nebo GoPay) je to popisované jako "cents"
